-- ============================================
-- GAMEVAULT DATABASE SEED DATA
-- Sample data for development and testing
-- ============================================

-- Create companies table if not exists (compatibility)
CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    logo_url VARCHAR(500),
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    country VARCHAR(100),
    founded_year INTEGER,
    closure_year INTEGER,
    acquired_by INTEGER REFERENCES companies(id) ON DELETE SET NULL,
    website VARCHAR(500),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample users
INSERT INTO users (name, email, password_hash, user_type, created_at, updated_at) VALUES
('Admin User', 'admin@gamevault.com', '$2b$10$hFQCk5STnxro6F.UqrybsOBbj6v5k3O3i0L3MqN1zI7FIwofH3u/W', 'admin', NOW(), NOW()),
('John Doe', 'john@example.com', '$2b$10$hFQCk5STnxro6F.UqrybsOBbj6v5k3O3i0L3MqN1zI7FIwofH3u/W', 'regular', NOW(), NOW()),
('Jane Smith', 'jane@example.com', '$2b$10$hFQCk5STnxro6F.UqrybsOBbj6v5k3O3i0L3MqN1zI7FIwofH3u/W', 'regular', NOW(), NOW())
ON CONFLICT (email) DO NOTHING;

-- Insert sample platforms
INSERT INTO platforms (name, slug, manufacturer, platform_type, generation, release_year, created_at, updated_at) VALUES
('PlayStation 5', 'ps5', 'Sony', 'console', 9, 2020, NOW(), NOW()),
('Xbox Series X', 'xbox-series-x', 'Microsoft', 'console', 9, 2020, NOW(), NOW()),
('Nintendo Switch', 'nintendo-switch', 'Nintendo', 'handheld', 8, 2017, NOW(), NOW()),
('PC', 'pc', 'Various', 'pc', NULL, NULL, NOW(), NOW()),
('PlayStation 4', 'ps4', 'Sony', 'console', 8, 2013, NOW(), NOW()),
('Xbox One', 'xbox-one', 'Microsoft', 'console', 8, 2013, NOW(), NOW()),
('Nintendo 3DS', 'nintendo-3ds', 'Nintendo', 'handheld', 8, 2011, NOW(), NOW()),
('iOS', 'ios', 'Apple', 'mobile', NULL, 2007, NOW(), NOW()),
('Android', 'android', 'Google', 'mobile', NULL, 2008, NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;

-- Insert sample companies (developers/publishers)
INSERT INTO companies (name, slug, country, founded_year, status, website, created_at, updated_at) VALUES
('Nintendo', 'nintendo', 'Japan', 1889, 'active', 'https://www.nintendo.com', NOW(), NOW()),
('Sony Interactive Entertainment', 'sony-interactive', 'Japan', 1993, 'active', 'https://www.sie.com', NOW(), NOW()),
('Microsoft Studios', 'microsoft-studios', 'USA', 2002, 'active', 'https://www.xbox.com/games', NOW(), NOW()),
('CD Projekt Red', 'cd-projekt-red', 'Poland', 2002, 'active', 'https://www.cdprojektred.com', NOW(), NOW()),
('Rockstar Games', 'rockstar-games', 'USA', 1998, 'active', 'https://www.rockstargames.com', NOW(), NOW()),
('Valve', 'valve', 'USA', 1996, 'active', 'https://www.valvesoftware.com', NOW(), NOW()),
('FromSoftware', 'fromsoftware', 'Japan', 1986, 'active', 'https://www.fromsoftware.jp', NOW(), NOW()),
('Bethesda Game Studios', 'bethesda-game-studios', 'USA', 2001, 'active', 'https://bethesdagamestudios.com', NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;

-- Insert sample games with real cover images
INSERT INTO games (
  title, slug, description, synopsis, release_year, release_date,
  cover_url, release_status, availability_status, age_rating, metacritic_score, created_at, updated_at
) VALUES
-- Nintendo Games
(
  'The Legend of Zelda: Breath of the Wild',
  'zelda-breath-of-the-wild',
  'An open-world action-adventure game set in a fantasy world where players explore, fight enemies, and solve puzzles.',
  'Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild.',
  2017,
  '2017-03-03',
  'https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
  'released',
  'available',
  'E10+',
  97,
  NOW(),
  NOW()
),
(
  'The Legend of Zelda: Tears of the Kingdom',
  'zelda-tears-of-the-kingdom',
  'An epic adventure across the land and skies of Hyrule awaits. Discover new powers and solve puzzles as you explore.',
  'An epic adventure across the land and skies of Hyrule awaits in this sequel to The Legend of Zelda: Breath of the Wild.',
  2023,
  '2023-05-12',
  'https://upload.wikimedia.org/wikipedia/en/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg',
  'released',
  'available',
  'E10+',
  96,
  NOW(),
  NOW()
),
(
  'Super Mario Odyssey',
  'super-mario-odyssey',
  'Join Mario on a massive, globe-trotting 3D adventure and use his incredible new abilities to collect Moons.',
  'Mario embarks on a new journey through unknown worlds, running and jumping through huge 3D worlds.',
  2017,
  '2017-10-27',
  'https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg',
  'released',
  'available',
  'E10+',
  97,
  NOW(),
  NOW()
),
(
  'Animal Crossing: New Horizons',
  'animal-crossing-new-horizons',
  'Escape to a deserted island and create your own paradise as you explore, create, and customize.',
  'Build your community from scratch on a deserted island brimming with possibility.',
  2020,
  '2020-03-20',
  'https://upload.wikimedia.org/wikipedia/en/1/1f/Animal_Crossing_New_Horizons.jpg',
  'released',
  'available',
  'E',
  90,
  NOW(),
  NOW()
),
(
  'Metroid Dread',
  'metroid-dread',
  'Join bounty hunter Samus Aran as she escapes a deadly alien world plagued by a mechanical menace.',
  'Samus faces her most terrifying mission yet in this 2D Metroid adventure.',
  2021,
  '2021-10-08',
  'https://upload.wikimedia.org/wikipedia/en/6/6e/Metroid_Dread_Cover_Art.jpg',
  'released',
  'available',
  'T',
  88,
  NOW(),
  NOW()
),

-- CD Projekt Red Games
(
  'Cyberpunk 2077',
  'cyberpunk-2077',
  'An open-world, action-adventure RPG set in the megalopolis of Night City.',
  'In Night City, a mercenary known as V navigates a dark future where violence and cyberware are commonplace.',
  2020,
  '2020-12-10',
  'https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg',
  'released',
  'available',
  'M',
  86,
  NOW(),
  NOW()
),
(
  'The Witcher 3: Wild Hunt',
  'the-witcher-3-wild-hunt',
  'An open-world action RPG set in a visually stunning fantasy universe full of meaningful choices.',
  'As war rages on throughout the Northern Realms, you take on the greatest contract of your life.',
  2015,
  '2015-05-19',
  'https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg',
  'released',
  'available',
  'M',
  93,
  NOW(),
  NOW()
),

-- FromSoftware Games
(
  'Elden Ring',
  'elden-ring',
  'A dark fantasy action RPG with vast world exploration and challenging combat.',
  'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring.',
  2022,
  '2022-02-25',
  'https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg',
  'released',
  'available',
  'M',
  96,
  NOW(),
  NOW()
),
(
  'Dark Souls III',
  'dark-souls-3',
  'A dark fantasy action RPG with punishing combat and interconnected world design.',
  'As fires fade and the world falls into ruin, journey into a universe full of more colossal enemies and environments.',
  2016,
  '2016-04-12',
  'https://upload.wikimedia.org/wikipedia/en/b/bb/Dark_souls_3_cover_art.jpg',
  'released',
  'available',
  'M',
  89,
  NOW(),
  NOW()
),
(
  'Sekiro: Shadows Die Twice',
  'sekiro-shadows-die-twice',
  'A brutally challenging action-adventure set in Sengoku-era Japan with innovative combat.',
  'Carve your own path to vengeance in this action-adventure from FromSoftware.',
  2019,
  '2019-03-22',
  'https://upload.wikimedia.org/wikipedia/en/6/6e/Sekiro_art.jpg',
  'released',
  'available',
  'M',
  90,
  NOW(),
  NOW()
),
(
  'Bloodborne',
  'bloodborne',
  'A dark and atmospheric action RPG set in a nightmarish Gothic Victorian city.',
  'Face your fears as you search for answers in the ancient city of Yharnam.',
  2015,
  '2015-03-24',
  'https://upload.wikimedia.org/wikipedia/en/6/68/Bloodborne_Cover_Wallpaper.jpg',
  'released',
  'available',
  'M',
  92,
  NOW(),
  NOW()
),

-- Sony Exclusive Games
(
  'The Last of Us Part II',
  'the-last-of-us-part-2',
  'An action-adventure game set in a post-apocalyptic world.',
  'Five years after their dangerous journey across the post-pandemic United States, Ellie and Joel have settled down.',
  2020,
  '2020-06-19',
  'https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png',
  'released',
  'available',
  'M',
  93,
  NOW(),
  NOW()
),
(
  'God of War Ragnarök',
  'god-of-war-ragnarok',
  'Kratos and Atreus journey through the Nine Realms seeking answers as Ragnarök approaches.',
  'Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go.',
  2022,
  '2022-11-09',
  'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg',
  'released',
  'available',
  'M',
  94,
  NOW(),
  NOW()
),
(
  'God of War (2018)',
  'god-of-war-2018',
  'A bold new beginning for Kratos with his son Atreus in the realm of Norse mythology.',
  'Kratos is a father again. As mentor and protector to Atreus, he must face the gods of a new realm.',
  2018,
  '2018-04-20',
  'https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg',
  'released',
  'available',
  'M',
  94,
  NOW(),
  NOW()
),
(
  'Horizon Forbidden West',
  'horizon-forbidden-west',
  'Join Aloy as she braves a majestic but dangerous frontier to find the source of a mysterious plague.',
  'Explore distant lands, fight bigger and more machines, and encounter astonishing tribes.',
  2022,
  '2022-02-18',
  'https://upload.wikimedia.org/wikipedia/en/6/69/Horizon_Forbidden_West_cover_art.jpg',
  'released',
  'available',
  'T',
  88,
  NOW(),
  NOW()
),
(
  'Ghost of Tsushima',
  'ghost-of-tsushima',
  'An open-world action-adventure samurai game set on Tsushima Island during the Mongol invasion.',
  'In the late 13th century, the Mongol empire has laid waste to entire nations. Jin Sakai, one of the last surviving samurai, must forge a new path.',
  2020,
  '2020-07-17',
  'https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg',
  'released',
  'available',
  'M',
  83,
  NOW(),
  NOW()
),
(
  'Spider-Man (PS4)',
  'spider-man-ps4',
  'Experience the iconic web-slinger in a new action-adventure game from Insomniac Games.',
  'Be greater. Experience the story of an experienced Peter Parker facing an all-new threat.',
  2018,
  '2018-09-07',
  'https://upload.wikimedia.org/wikipedia/en/e/e1/Spider-Man_PS4_cover.jpg',
  'released',
  'available',
  'T',
  87,
  NOW(),
  NOW()
),
(
  'Spider-Man: Miles Morales',
  'spider-man-miles-morales',
  'Experience the rise of Miles Morales as the new hero masters incredible powers to protect his home.',
  'In the latest adventure in the Marvel''s Spider-Man universe, teenager Miles Morales adjusts to his new home.',
  2020,
  '2020-11-12',
  'https://upload.wikimedia.org/wikipedia/en/3/3e/Spider-Man_Miles_Morales.png',
  'released',
  'available',
  'T',
  85,
  NOW(),
  NOW()
),

-- Rockstar Games
(
  'Red Dead Redemption 2',
  'red-dead-redemption-2',
  'An epic tale of life in America at the dawn of the modern age.',
  'Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and bounty hunters on their heels.',
  2018,
  '2018-10-26',
  'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
  'released',
  'available',
  'M',
  97,
  NOW(),
  NOW()
),
(
  'Grand Theft Auto V',
  'grand-theft-auto-v',
  'An open-world action-adventure game set in the fictional state of San Andreas.',
  'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld.',
  2013,
  '2013-09-17',
  'https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png',
  'released',
  'available',
  'M',
  97,
  NOW(),
  NOW()
),

-- Bethesda Games
(
  'Starfield',
  'starfield',
  'An epic role-playing game set among the stars exploring the greatest mystery of humanity.',
  'In this new generation role-playing game set amongst the stars, create any character you want and explore with unparalleled freedom.',
  2023,
  '2023-09-06',
  'https://upload.wikimedia.org/wikipedia/en/6/6d/Starfield_cover.jpg',
  'released',
  'available',
  'M',
  83,
  NOW(),
  NOW()
),
(
  'The Elder Scrolls V: Skyrim',
  'the-elder-scrolls-v-skyrim',
  'An open-world RPG set in the northern province of Tamriel where dragons have returned.',
  'The Empire of Tamriel is on the edge. The High King of Skyrim has been murdered. Dragons, long thought dead, are returning.',
  2011,
  '2011-11-11',
  'https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png',
  'released',
  'available',
  'M',
  94,
  NOW(),
  NOW()
),
(
  'Fallout 4',
  'fallout-4',
  'An open-world RPG set in a post-apocalyptic Boston, 200 years after a nuclear war.',
  'As the sole survivor of Vault 111, you enter a world destroyed by nuclear war seeking your son.',
  2015,
  '2015-11-10',
  'https://upload.wikimedia.org/wikipedia/en/7/70/Fallout_4_cover_art.jpg',
  'released',
  'available',
  'M',
  84,
  NOW(),
  NOW()
),

-- Square Enix Games
(
  'Final Fantasy VII Remake',
  'final-fantasy-vii-remake',
  'A spectacular reimagining of one of the most visionary games ever, rebuilt for modern platforms.',
  'Cloud Strife, a former member of SOLDIER now turned mercenary, lends his aid to an Eco-terrorist group.',
  2020,
  '2020-04-10',
  'https://upload.wikimedia.org/wikipedia/en/c/ce/FFVIIRemake.png',
  'released',
  'available',
  'T',
  87,
  NOW(),
  NOW()
),
(
  'Final Fantasy XVI',
  'final-fantasy-xvi',
  'An action RPG that brings players into a dark fantasy world as they embark on an epic journey.',
  'The fate of the land is decided by the Eikons and the Dominants who wield them.',
  2023,
  '2023-06-22',
  'https://upload.wikimedia.org/wikipedia/en/3/30/Final_Fantasy_XVI_cover_art.png',
  'released',
  'available',
  'M',
  87,
  NOW(),
  NOW()
),
(
  'Kingdom Hearts III',
  'kingdom-hearts-3',
  'Join Sora, Donald and Goofy in their most magical adventure yet across Disney and Pixar worlds.',
  'Sora, Donald, and Goofy unite with iconic Disney-Pixar characters to battle darkness.',
  2019,
  '2019-01-29',
  'https://upload.wikimedia.org/wikipedia/en/8/8b/Kingdom_Hearts_III_box_art.jpg',
  'released',
  'available',
  'E10+',
  83,
  NOW(),
  NOW()
),

-- Capcom Games
(
  'Resident Evil Village',
  'resident-evil-village',
  'Experience survival horror like never before in the eighth major installment.',
  'Set a few years after the events of Resident Evil 7, Ethan Winters'' peaceful life is shattered.',
  2021,
  '2021-05-07',
  'https://upload.wikimedia.org/wikipedia/en/2/2c/Resident_Evil_Village.png',
  'released',
  'available',
  'M',
  84,
  NOW(),
  NOW()
),
(
  'Monster Hunter: World',
  'monster-hunter-world',
  'Hunt alone or in a party with friends to slay powerful monsters in an evolving ecosystem.',
  'Welcome to a new world! Take on the role of a hunter and slay ferocious monsters.',
  2018,
  '2018-01-26',
  'https://upload.wikimedia.org/wikipedia/en/1/1b/Monster_Hunter_World_cover_art.jpg',
  'released',
  'available',
  'T',
  90,
  NOW(),
  NOW()
),
(
  'Devil May Cry 5',
  'devil-may-cry-5',
  'A brand new entry in the legendary action series that reunites iconic characters.',
  'Years have passed since the demon king was defeated. A new threat has arisen.',
  2019,
  '2019-03-08',
  'https://upload.wikimedia.org/wikipedia/en/c/cb/Devil_May_Cry_5.jpg',
  'released',
  'available',
  'M',
  88,
  NOW(),
  NOW()
),
(
  'Street Fighter 6',
  'street-fighter-6',
  'A new era of fighting games begins with revolutionary controls and modern gameplay.',
  'The evolution of fighting games starts here with the newest entry in the legendary franchise.',
  2023,
  '2023-06-02',
  'https://images.igdb.com/igdb/image/upload/t_cover_big/co5vmg.jpg',
  'released',
  'available',
  'T',
  92,
  NOW(),
  NOW()
),

-- Other Major Games
(
  'Hogwarts Legacy',
  'hogwarts-legacy',
  'An immersive, open-world action RPG set in the world of Harry Potter during the 1800s.',
  'Experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret.',
  2023,
  '2023-02-10',
  'https://upload.wikimedia.org/wikipedia/en/d/d7/Hogwarts_Legacy_cover_art.png',
  'released',
  'available',
  'T',
  84,
  NOW(),
  NOW()
),
(
  'Baldur''s Gate 3',
  'baldurs-gate-3',
  'A story-rich, party-based RPG set in the universe of Dungeons & Dragons.',
  'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.',
  2023,
  '2023-08-03',
  'https://upload.wikimedia.org/wikipedia/en/1/12/Baldur%27s_Gate_3_cover_art.jpg',
  'released',
  'available',
  'M',
  96,
  NOW(),
  NOW()
),
(
  'Hades',
  'hades',
  'A rogue-like dungeon crawler where you battle your way out of the Underworld.',
  'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler.',
  2020,
  '2020-09-17',
  'https://upload.wikimedia.org/wikipedia/en/1/1a/Hades_cover_art.jpg',
  'released',
  'available',
  'T',
  93,
  NOW(),
  NOW()
),
(
  'Hollow Knight',
  'hollow-knight',
  'A challenging 2D action-adventure through a hauntingly beautiful ruined kingdom of insects.',
  'Forge your own path in Hollow Knight! An epic action adventure through a vast kingdom.',
  2017,
  '2017-02-24',
  'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg',
  'released',
  'available',
  'E10+',
  90,
  NOW(),
  NOW()
),
(
  'Celeste',
  'celeste',
  'A challenging platformer about climbing a mountain where you help Madeline survive her inner demons.',
  'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain.',
  2018,
  '2018-01-25',
  'https://images.igdb.com/igdb/image/upload/t_cover_big/co2p3d.jpg',
  'released',
  'available',
  'E10+',
  92,
  NOW(),
  NOW()
),
(
  'Stardew Valley',
  'stardew-valley',
  'A farming simulation game where you inherit your grandfathers old farm plot.',
  'You have inherited your grandfathers old farm plot in Stardew Valley. Build the farm of your dreams.',
  2016,
  '2016-02-26',
  'https://images.igdb.com/igdb/image/upload/t_cover_big/co2ed5.jpg',
  'released',
  'available',
  'E10+',
  89,
  NOW(),
  NOW()
),
(
  'Disco Elysium',
  'disco-elysium',
  'A groundbreaking role-playing game where you are a detective with a unique skill system.',
  'You are a detective with a unique skill system at your disposal and a whole city to carve your path across.',
  2019,
  '2019-10-15',
  'https://upload.wikimedia.org/wikipedia/en/3/36/Disco_Elysium_cover_art.jpg',
  'released',
  'available',
  'M',
  91,
  NOW(),
  NOW()
),
(
  'Outer Wilds',
  'outer-wilds',
  'An open-world mystery about a solar system trapped in an endless time loop.',
  'Explore a strange, beautiful solar system stuck in an endless time loop in this acclaimed adventure.',
  2019,
  '2019-05-28',
  'https://upload.wikimedia.org/wikipedia/en/e/e6/Outer_Wilds_cover_art.png',
  'released',
  'available',
  'E10+',
  85,
  NOW(),
  NOW()
),
(
  'It Takes Two',
  'it-takes-two',
  'A genre-bending platform adventure built purely for co-op.',
  'Cody and May are a couple on the brink of divorce. Together, you must fix what was broken.',
  2021,
  '2021-03-26',
  'https://upload.wikimedia.org/wikipedia/en/b/bb/It_Takes_Two_cover_art.jpg',
  'released',
  'available',
  'T',
  88,
  NOW(),
  NOW()
),
(
  'Doom Eternal',
  'doom-eternal',
  'The ultimate combination of speed and power with the next leap in first-person combat.',
  'Raze Hell with the DOOM Slayer. Experience the ultimate combination of speed and power.',
  2020,
  '2020-03-20',
  'https://upload.wikimedia.org/wikipedia/en/9/9a/Doom_Eternal.jpg',
  'released',
  'available',
  'M',
  88,
  NOW(),
  NOW()
),

-- Upcoming/Recent Games
(
  'GTA VI',
  'gta-6',
  'The next installment in the legendary Grand Theft Auto series.',
  'Return to Vice City in the biggest, most immersive Grand Theft Auto experience yet.',
  2025,
  '2025-10-01',
  'https://upload.wikimedia.org/wikipedia/en/a/a6/Grand_Theft_Auto_VI_cover.jpg',
  'coming_soon',
  'available',
  'M',
  NULL,
  NOW(),
  NOW()
),
(
  'Silksong',
  'silksong',
  'Play as Hornet and descend into a new kingdom in the sequel to Hollow Knight.',
  'The sequel to Hollow Knight! Discover a vast new kingdom in this challenging adventure.',
  2025,
  NULL,
  'https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5v.jpg',
  'in_development',
  'available',
  'E10+',
  NULL,
  NOW(),
  NOW()
),
(
  'Metroid Prime 4: Beyond',
  'metroid-prime-4',
  'The next chapter in the Metroid Prime series returns to the first-person adventure genre.',
  'Samus returns in a brand-new Metroid Prime adventure.',
  2025,
  '2025-12-31',
  'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ycw.jpg',
  'in_development',
  'available',
  'T',
  NULL,
  NOW(),
  NOW()
),

-- Classic/Retro Games (for preservation)
(
  'Chrono Trigger',
  'chrono-trigger',
  'A legendary RPG where a group of time travelers journey across eras to save the world.',
  'Journey through time to save the world in this legendary RPG masterpiece.',
  1995,
  '1995-03-11',
  'https://upload.wikimedia.org/wikipedia/en/a/a7/Chrono_Trigger.jpg',
  'released',
  'available',
  'E10+',
  92,
  NOW(),
  NOW()
),
(
  'Super Metroid',
  'super-metroid',
  'Return to Planet Zebes in one of the greatest 2D action-adventure games ever made.',
  'Samus Aran returns to Planet Zebes to rescue the last Metroid from the Space Pirates.',
  1994,
  '1994-03-19',
  'https://upload.wikimedia.org/wikipedia/en/e/e4/Super_Metroid_Box.jpg',
  'released',
  'available',
  'E',
  96,
  NOW(),
  NOW()
),
(
  'Half-Life 2',
  'half-life-2',
  'A revolutionary first-person shooter that set new standards for storytelling and physics.',
  'Dr. Gordon Freeman awakens in a dystopian City 17 to lead a resistance against an alien empire.',
  2004,
  '2004-11-16',
  'https://upload.wikimedia.org/wikipedia/en/2/25/Half-Life_2_cover.jpg',
  'released',
  'available',
  'M',
  96,
  NOW(),
  NOW()
),
(
  'Portal 2',
  'portal-2',
  'A puzzle-platform game featuring innovative portal mechanics and dark humor.',
  'Awaken in Aperture Science and use the Portal Gun to escape while solving mind-bending puzzles.',
  2011,
  '2011-04-19',
  'https://upload.wikimedia.org/wikipedia/en/f/f9/Portal2cover.jpg',
  'released',
  'available',
  'E10+',
  95,
  NOW(),
  NOW()
),
(
  'BioShock',
  'bioshock',
  'A shooter set in the underwater city of Rapture with unique powers and moral choices.',
  'Discover the failed utopia of Rapture, a city beneath the sea where idealism has fallen to madness.',
  2007,
  '2007-08-21',
  'https://upload.wikimedia.org/wikipedia/en/6/6d/BioShock_cover.jpg',
  'released',
  'available',
  'M',
  96,
  NOW(),
  NOW()
),
(
  'Mass Effect 2',
  'mass-effect-2',
  'An action RPG where you assemble a team of heroes to save the galaxy from the Collectors.',
  'Commander Shepard returns to assemble a team of elite specialists for a suicide mission.',
  2010,
  '2010-01-26',
  'https://upload.wikimedia.org/wikipedia/en/0/05/MassEffect2_cover.PNG',
  'released',
  'available',
  'M',
  94,
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO NOTHING;

-- Insert genres
INSERT INTO genres (name, slug, description, created_at) VALUES
('Action', 'action', 'Fast-paced gameplay with physical challenges', NOW()),
('Adventure', 'adventure', 'Exploration and story-driven gameplay', NOW()),
('RPG', 'rpg', 'Role-playing games with character progression', NOW()),
('Strategy', 'strategy', 'Games requiring tactical planning', NOW()),
('Simulation', 'simulation', 'Games that simulate real-world activities', NOW()),
('Sports', 'sports', 'Athletic and competitive games', NOW()),
('Puzzle', 'puzzle', 'Games focused on problem-solving', NOW()),
('Horror', 'horror', 'Games designed to frighten and create tension', NOW()),
('Shooter', 'shooter', 'Games centered around gun combat', NOW()),
('Fighting', 'fighting', 'One-on-one combat games', NOW())
ON CONFLICT (slug) DO NOTHING;

COMMIT;
